name: Build & Deploy

on:
  push:

    branches:
      - "main"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm ci --force
      - name: Build
        run: npm run build
      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: deploy_dist
          path: dist
      - name: Archive code coverage result
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ~/files_art/

  deploy: 
      needs: build
      runs-on: ubuntu-latest
      environment: Development
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Connect to Server
          uses: appleboy/scp-action@v0.1.4
          with: 
            host: ${{secrets.SSH_HOST}}
            key: ${{secrets.SSH_KEY}}
            username: ${{secrets.SSH_USERNAME}}
            source: "~/files_art/artifact/"
            target: "/var/www/bookreviews.uz/html/"
            recursive: true

          
          
        

        
