name: Build & Deploy

on:
  push:

    branches:
      - "main"

jobs:
  build:
    name: Build
    environment: Development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm ci --force
      - name: Build
        run: npm run build
      - uses: actions/checkout@v3
      - name: Connect to Server
        uses: appleboy/scp-action@master
        with: 
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          source: "dist/*"
          target: "/var/www/bookreviews.uz/html/"

          
          
        

        
