name: Build & Deploy

on:
  push:

    branches:
      - "main"

jobs:
  clone_repo: 
      runs-on: ubuntu-latest
      environment: Development
      steps:
        - name: Clone repository
          uses: appleboy/ssh-action@v1.0.0
          with: 
            host: ${{secrets.SSH_HOST}}
            key: ${{secrets.SSH_KEY}}
            username: ${{secrets.SSH_USERNAME}}
            srcipts: |
              cd /server
              mdir piggy-bank-frontend
              cd piggy-bank-frontend
              git clone git@github.com:asadbek2021/piggy-bank-front.git
              print 'Cloned successfully!'

  deploy:
    needs: clone_repo
    runs-on: ubuntu-latest
    environment: Development
    strategy:
      matrix:
        node-version: ['16.x', '18.x']
    steps:
      - name: Check for node version
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - run: cd /server/
      - run: npm ci; npm run build; npm run start
      - run: echo 'Successfully deployed'

          
          
        

        
