name: Build & Deploy

on:
  push:

    branches:
      - "main"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm ci --force
      - name: Build
        run: npm run build
      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: deploy_dist
          path: dist
      - name: Archive code coverage result
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: deploy_coverage
          path: coverage

  deploy: 
      needs: build
      strategy:
          matrix:
            node-version: ['16.x', '18.x']
      runs-on: ubuntu-latest
      environment: Development
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Download build
          uses: appleboy/ssh-action@v1.0.0
          with: 
            host: ${{secrets.SSH_HOST}}
            key: ${{secrets.SSH_KEY}}
            username: ${{secrets.SSH_USERNAME}}
            srcipts: |
              cd /server
              mdir piggy-bank-front
              cd piggy-bank-front
        - name: Download build
          uses: actions/download-artifact@v3
          with:
            name: my-artifact
            path: /server/piggy-bank-front
        - name: Display structure of downloaded files
          run: ls -R
          working-directory: /server/piggy-bank-front
        - name: 'Echo download path'
          run: echo ${{steps.download.outputs.download-path}}
        - run: echo 'Successfully deployed'

          
          
        

        
